name: adote_pets
description: Um app para facilitar a adoção de pets.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  dio: ^4.0.6
  lottie: ^1.3.0
  asuka: ^2.0.0+1
  shared_preferences: ^2.0.15
  google_fonts: 2.2.0
  fancy_shimmer_image: ^2.0.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash.png"
flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/animations/splash.json
